source 'https://rubygems.org'
gem 'capybara'
gem 'csv'
gem 'gmail'
gem 'pdf-reader', '~> 1.4'
gem 'pry'
gem 'pry-nav'
gem 'rspec', '>= 3.2'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'airborne'
gem 'allure-rspec', '>= 0.7.7'
gem 'byebug'
gem 'parallel-rspec'
gem 'appium_capybara'
gem 'site_prism'
gem 'appium_lib', '>= 9.15.0'
gem 'touch_action'
# gem 'spreadsheet'
gem 'chromedriver-helper', '~>1.2.0'
gem 'parallel_tests'
gem 'concurrent-ruby'
gem 'roo'
gem 'rspec_html_reporter'

